name: Release

on:
  release:
    types: [published]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v2
      - uses: Swatinem/rust-cache@v1
      - name: Build release (Windows)
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --target=x86_64-pc-windows-msvc
      - name: Build archive
        run: |
          Compress-Archive -Path target\x86_64-pc-windows-msvc\release\usbrawmap.exe, usbrawmap.toml -DestinationPath release.zip
      - name: Upload binary
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          asset_name: usbrawmap-${{ github.event.release.tag_name }}-x86_64.zip
          asset_path: release.zip
          asset_content_type: application/x-zip
          upload_url: ${{ github.event.release.upload_url }}
